# Database connection URL (Postgres)
database_url: "postgres://stratum_user:qwerty123@localhost:5432/stratum?sslmode=disable"

# HTTP server port
server_port: "8080"

# JWT secret key for signing tokens
jwt_secret: "this_is_a_very_secret_key"
